### ISSUE TITLE
Question about the suffix ’WD‘

### ISSUE THREAD

**Issue by Gatsby23** [Eskilade/orient#1]
Notice that in different rotation representation the jacobian calculation always use suffix 'WD', right？ But what does the 'WD' mean ? I wonder if it represent which component to derive?

**Comment by Eskilade** [comment]
"WD" is short for "with derivative" and is indeed used to signify that the Jacobian of the transformation is also calculated :)

**Comment by Gatsby23** [comment]
> "WD" is short for "with derivative" and is indeed used to signify that the Jacobian of the transformation is also calculated :)

OK! Thank you very much!
